# NumPy Exercises

Reference for some of these exercises is [here](https://www.w3resource.com/python-exercises/).

## Exercise 1

Write a NumPy program to create a random array with 100 real-valued elements between 1 & 5 and compute the following for this array rounded to 2 decimal places:
- average (that is, the sample mean)
- population variance and population standard deviation (default option in NumPy)
- sample variance and sample standard deviation

**Hint:** For sample variance and sample standard deviation, use the `ddof=1` parameter value.

**Explanations**

Population variance

$$\text{Population variance} = \frac{\sum_{i=1}^{N}(X_i - \bar{X})^{2}}{N}$$

Sample variance

$$\text{Sample variance} = \frac{\sum_{i=1}^{N}(X_i - \bar{X})^{2}}{N-1}$$

In [78]:
import numpy as np

arr = np.array((np.random.rand(100) * 4) + 1)
np.var(arr)
np.std(arr)
# we have our array

print(((np.sum(arr)) / len(arr)).round(2))
print((np.var(arr)).round(2))
print((np.std(arr)).round(2))


def calc_variance(arr):
    mean_arr = ((np.sum(arr)) / len(arr)).round(2)
    numerator = 0
    diff_from_mean = []
    for i in range(0, len(arr),1):
        diff_from_mean.append(arr[i] - mean_arr)
        numerator = numerator + (diff_from_mean[i]**2)
    variance_x = numerator / (len(arr) - 1)
    return variance_x

print(calc_variance(arr).round(2))
print(np.var(arr, ddof=1).round(2))
print(np.std(arr, ddof=1).round(2))




2.98
1.36
1.16
1.37
1.37
1.17


## Execise 2

Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array. 

In [121]:
x = 5 + np.arange(10)

print(x[x > 10])
print(np.nonzero (x > 10)[0])

[11 12 13 14]
[6 7 8 9]


## Exercise 3

Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in the first array `array1` that are not in the second one `array2`. **Hint:** This is a one-liner.

In [126]:
arr1 = ([2, 4, 6, 8, 10, 12])
arr2 = ([3, 6, 9, 12])
print(np.setdiff1d(arr1, arr2))

[ 2  4  8 10]


## Exercise 4

Write a NumPy program to calculate element-wise round, floor, ceiling, and truncated form of an input array.

In [139]:
arr = np.array([2.37, 2.72, 3.69, 4.12, 4.93])

print(np.round(arr).astype(int))
print(np.floor(arr).astype(int))
print(np.ceil(arr).astype(int))
print(np.trunc(arr).astype(int))

[2 3 4 4 5]
[2 2 3 4 4]
[3 3 4 5 5]
[2 2 3 4 4]


***
www.featureranking.com